#!/bin/bash
__scriptVersion=0.1
__scriptPID=$$
__scriptPath="$(dirname "$0")"
__scriptFile="$(basename "$0")"

# Function ========================================================   
#           Name:  vnc
#         Author:  Rusty Gibbs 
#       Homepage:  http://www.wickedidol.com
#            Git:  https://github.com/fenchurch/dotfiles/bin
#    Description:  vnc
#        Created:  2018-04-12
#       Modified:  2018-04-12
# ================================================================= 

#Settings
config=~/.ssh/config
timeout=1
ignore=( git wi vw )
defaultPort=5900

host="${1##*@}"
cred="${1%@*}"
if [[ "$host" != "${host%:*}" ]]; then 
    port=${host%:*}
    host=${host##*:}
else
    port=$defaultPort
fi

join(){  IFS=$1; shift; echo "$*"; }
sshHosts(){
    awk '/Host / { host=$2; }; /Hostname / && host!="" { print host }' $config | grep -Ev $(join '|' ${ignore[*]}) 
}
host(){
    awk '/Host '$1'$/ { host=1; }; /Hostname / && host==1 { print $2; host=0 }' $config
}
selectHost(){
    PS3="Select a host (type quit to cancel) : "
    select opt in `sshHosts`; do
        case $REPLY in
        q|n|quit|cancel|exit)
            exit;;
        * )
            hostO=$(host $opt)
            hostR=$(host $REPLY)
            if [[ "$hostO" == "" && "$hostR" == "" ]]; then
                echo "Invalid answer, try again..."
            elif [[ "$hostO" != "" ]]; then
                echo "$hostO"
                break;
            elif [[ "$hostR" != "" ]]; then
                echo "$hostR"
                break;
            fi;;
        esac
    done
}
main(){
    [[ "$host" == "" ]] && host=$(selectHost) || sshhost=$(host $host)
    [[ "$sshhost" != "" ]] && host="$sshhost" || :
    [[ "$cred" == "$host" ]] && cred="" || cred="$cred@"

    if nc -G$timeout -z $host $port 2>&-; then
        echo "Opening vnc to $host on port $port"
        open vnc://"$cred$host:$port"
    else
        echo -e "\e[31mVNC port ($port) not open on $host\e[30m"
        return 1;
    fi
}
main
