#!/bin/bash
#install brew if not installed
cd "$(dirname "$0")"
which brew 1>&- || ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
#update and upgrade
brew doctor && brew update && brew upgrade
#kegs to install
while read -r line; do
    line=${line%%#*};
    [[ -z "$line" ]] && continue
    brew install $line
done < brew.kegs
#casks to install
while read -r line; do
    line=${line%%#*};
    [[ -z "$line" ]] && continue;
    brew tap "$line"
done < brew.taps
while read -r line; do
    line=${line%%#*};
    [[ -z "$line" ]] && continue 
    brew cask install $line
done < brew.casks
