#!/bin/bash
#set -e
scriptPID=$$
scriptName="$(basename "$0")"
scriptPath="$( cd "$(dirname "$0")"; pwd -P )"
script="$scriptPath/$scriptName"

for file in `uname` all; do
    if [[ -f "$0.$file" ]]; then
	echo "Git: Cloning $file repos"  
        while read line; do
	    [ -z "$line" ] && continue;
            url=${line%=*} 
            loc=${line##*=}
	
            echo Cloning $url to $loc
            git clone "$url" "$HOME/$loc"
        done < "$0.$file"
    fi
done
