#!/bin/bash
scriptName=$(basename "$0")
scriptPath=$(dirname "$0")
scriptPID=$$

cd $HOME
for file in `uname` all; do
    echo $file
    if [[ -f "$0.$file" ]]; then
        while read line; do
            url=${line%=*} 
            loc=${line##*=}
            echo Cloning $url to $loc
            git clone $url $loc
        done < "$0.$file"
    fi
done
