#!/bin/bash
# Assuming using dropbox
ssh=${1:-~/Dropbox/dotfiles/.ssh}
user=${2:-~}

if [ ! -d "$ssh" ]; then 
    echo "No SSH directory to copy in $ssh";
else
    echo "Linking $ssh to $user"
    ln -s "$ssh" "$user"
fi
